name: Ubuntu

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        vcpkg install cryptopp
        sudo apt install g++-10
        mkdir build
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_CXX_COMPILER=g++-10
        cmake --build .
        strip src/app
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: /home/runner/work/Redux/Redux/build/src/app
