name: Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        vcpkg install cryptopp:x64-windows
        cmake -G "Visual Studio 16 2019" -A x64 -S . -B "build64" -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
        cmake --build build64 --config Release
    - name: Upload Windows Application
      uses: actions/upload-artifact@v2
      with:
        name: Windows-Applicationx64
        path: D:\a\Redux\Redux\build64\src\Release\app.exe