name: Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        vcpkg install cryptopp:x64-windows
        mkdir build
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
        cmake --build . --config Release
    - name: Upload Windows Application
      uses: actions/upload-artifact@v2
      with:
        name: Windows Application
        path: D:\a\Redux\Redux\build\src\Release\app.exe